### ISSUE TITLE
Published ports are not visible on nodes

### ISSUE THREAD

**Issue by 5ika** [jelastic-jps/docker-native#4]
Hi,
I try to create a Docker Swarm with some public services on it.
Firstly, I've installed a new env from the Marketplace on the hoster [Hidora](https://app.hidora.com) and checked for the Portainer installation.
Everything seemed to work fine but when I tried to get Portainer (swarm.hidora.com:9000), it doesn't find the page.
I've tried to launch more services in my cluster with published ports but no one is accessible (with default overlay network and with custom overlay net)

With `docker service ls`, I can see that my ports are correctly published by Docker but when I'm trying to see which ports are used on the Linux side (`ss -lnt`), none appear.

Is the problem on my side or is it a configuration problem ?
Thanks for your help

**Comment by ihorman** [comment]
@5ika, thank you for reporting the problem, we've found that there are some issues related to ip_vs configuration on servers on that particular hosting service provider, we will additionally update you once everything is fixed

**Comment by ihorman** [comment]
@5ika, it looks like this URL works now [https://swarm.hidora.com/#/auth](https://swarm.hidora.com/#/auth)
